### ISSUE TITLE
Couldn't Open the Site

### ISSUE THREAD

**Issue by athul** [haxzie-xx/awesome-movies-for-geeks#17]
I can't open the website https://geektube.netlify.com
I don't know if it's a rendering error or something but I get like this
![screenshot_20190103-171310](https://user-images.githubusercontent.com/40897573/50636148-032a2b00-0f7b-11e9-9db0-61a750e08e44.jpg)

**Comment by athul** [comment]
And I used rendered it as Desktop Site

**Comment by haxzie-xx** [comment]
It's still under development 😅

**Comment by Athul-CA** [comment]
Oh.. My bad😅Kind Regards,      Athul Cyriac Ajay -------- Original Message --------Subject: Re: [haxzie/awesome-movies-for-geeks] Couldn't Open the Site (#17)From: Musthaq Ahamad To: haxzie/awesome-movies-for-geeks CC: Athul Cyriac Ajay ,Author It's still under development 😅



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/haxzie/awesome-movies-for-geeks","title":"haxzie/awesome-movies-for-geeks","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/haxzie/awesome-movies-for-geeks"}},"updates":{"snippets":[{"icon":"PERSON","message":"@haxzie in #17: It's still under development 😅"}],"action":{"name":"View Issue","url":"https://github.com/haxzie/awesome-movies-for-geeks/issues/17#issuecomment-451142800"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/haxzie/awesome-movies-for-geeks/issues/17#issuecomment-451142800",

"url": "https://github.com/haxzie/awesome-movies-for-geeks/issues/17#issuecomment-451142800",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by athul** [comment]
Oh😅
